"""
Author: geralm
Final Production Version: Zero-Memory Stream Ingestion.
Bypasses Python ORM overhead, cleans null bytes (\x00) on the fly, 
and uses explicit, armored PostgreSQL C-level type casting.
"""

import os
import re
import csv
import logging
import sqlalchemy as sa
from sqlalchemy import text
from sqlmodel import Session, SQLModel

from core.database import get_engine
from core.models import (
    Buildings, Participants, Apartments, Employers, Pubs, 
    Restaurants, Schools, Jobs, CheckinJournal, FinancialJournal, 
    SocialNetwork, TravelJournal, ActivityLogs
)

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("db_init")

engine = get_engine()
DATA_ROOT = os.getenv("DATA_PATH", "../data")
ACTIVITY_LOGS_PATH = os.path.join(DATA_ROOT, "Activity Logs")

INGESTION_PLAN = [
    (os.path.join(DATA_ROOT, "Attributes/Buildings.csv"), Buildings),
    (os.path.join(DATA_ROOT, "Attributes/Participants.csv"), Participants),
    (os.path.join(DATA_ROOT, "Attributes/Apartments.csv"), Apartments),
    (os.path.join(DATA_ROOT, "Attributes/Employers.csv"), Employers),
    (os.path.join(DATA_ROOT, "Attributes/Pubs.csv"), Pubs),
    (os.path.join(DATA_ROOT, "Attributes/Restaurants.csv"), Restaurants),
    (os.path.join(DATA_ROOT, "Attributes/Schools.csv"), Schools),
    (os.path.join(DATA_ROOT, "Attributes/Jobs.csv"), Jobs),
    (os.path.join(DATA_ROOT, "Journals/CheckinJournal.csv"), CheckinJournal),
    (os.path.join(DATA_ROOT, "Journals/FinancialJournal.csv"), FinancialJournal),
    (os.path.join(DATA_ROOT, "Journals/SocialNetwork.csv"), SocialNetwork),
    (os.path.join(DATA_ROOT, "Journals/TravelJournal.csv"), TravelJournal),
]

# -----------------------------------------------------------------------------
# Zero-Memory Stream Cleaner (The fix for \x00 in File 56)
# -----------------------------------------------------------------------------
class CleanCSVStream:
    """
    Reads the file in 8KB chunks, stripping null bytes (\x00) instantly.
    Memory usage is flat and nearly zero, bypassing Python's memory limits.
    """
    def __init__(self, filepath):
        self.file = open(filepath, 'r', encoding='utf-8-sig')
        
    def read(self, size=8192):
        chunk = self.file.read(size)
        return chunk.replace('\x00', '') if chunk else ""
        
    def close(self):
        self.file.close()

# -----------------------------------------------------------------------------
# Absolute SQL Type Generator & Armor
# -----------------------------------------------------------------------------
def get_csv_headers(filepath: str) -> list:
    with open(filepath, 'r', encoding='utf-8-sig') as f:
        first_line = f.readline().replace('\x00', '').strip()
        return next(csv.reader([first_line]))

def generate_insert_sql(model: Type[SQLModel], csv_cols: list, staging_table: str, filename: str) -> str:
    """Generates an explicit INSERT INTO ... SELECT ... CAST statement with strict sanitization."""
    target_cols = []
    select_exprs = []
    
    for c in model.__table__.columns:
        col_name = c.name
        target_cols.append(f'"{col_name}"')
        
        # 1. Autogenerated Fields
        if col_name == "id" and "id" not in csv_cols:
            select_exprs.append("gen_random_uuid()")
            continue
        if col_name == "file_meta":
            select_exprs.append(f"'{{\"filename\": \"{filename}\"}}'::JSONB")
            continue
            
        # 2. Skip missing columns
        if col_name not in csv_cols:
            select_exprs.append("NULL")
            continue
            
        # 3. Base Sanitization: Trim spaces AND literal double quotes from the CSV string
        base_val = f"TRIM(BOTH '\"' FROM TRIM(\"{col_name}\"))"
        
        ctype = c.type
        type_str = str(ctype).upper()
        
        # 4. Explicit Type Casting Rules (Flawless Python-to-Postgres mapping)
        if isinstance(ctype, sa.DateTime) or "DATETIME" in type_str:
            select_exprs.append(f"NULLIF({base_val}, '')::TIMESTAMPTZ")
            
        elif isinstance(ctype, sa.Time) or "TIME" in type_str:
            select_exprs.append(f"NULLIF({base_val}, '')::TIME")
            
        elif isinstance(ctype, sa.Integer) or "INT" in type_str:
            select_exprs.append(f"NULLIF({base_val}, '')::INTEGER")
            
        elif isinstance(ctype, (sa.Float, sa.Numeric)) or "FLOAT" in type_str or "NUMERIC" in type_str:
            select_exprs.append(f"NULLIF({base_val}, '')::DOUBLE PRECISION")
            
        elif isinstance(ctype, sa.Boolean) or "BOOL" in type_str:
            select_exprs.append(f"NULLIF({base_val}, '')::BOOLEAN")
            
        elif isinstance(ctype, sa.dialects.postgresql.JSONB) or "JSONB" in type_str:
            # Converts Python-style arrays ['a'] to strict JSON arrays ["a"] and defaults to []
            json_val = f"REPLACE({base_val}, '''', '\"')"
            select_exprs.append(f"COALESCE(NULLIF({json_val}, ''), '[]')::JSONB")
            
        elif getattr(ctype, "__class__", None).__name__ == "Enum" or "ENUM" in type_str:
            enum_name = ctype.name.lower() # Enums are lowercase in PG
            if col_name == "buildingType":
                # Hotfix for the typo in the datasets
                fixed_val = f"REPLACE({base_val}, 'Residental', 'Residential')"
                select_exprs.append(f"NULLIF({fixed_val}, '')::{enum_name}")
            else:
                select_exprs.append(f"NULLIF({base_val}, '')::{enum_name}")
                
        else:
            # TEXT Fallback
            select_exprs.append(f"NULLIF({base_val}, '')")
            
    insert_clause = ", ".join(target_cols)
    select_clause = ", ".join(select_exprs)
    
    return f'INSERT INTO "{model.__tablename__}" ({insert_clause}) SELECT {select_clause} FROM {staging_table}'

# -----------------------------------------------------------------------------
# Core Engine
# -----------------------------------------------------------------------------
def brutal_ingest(session: Session, file_path: str, model: Type[SQLModel], filename: str):
    conn = session.connection().connection
    csv_cols = get_csv_headers(file_path)
    
    import uuid
    staging_table = f"temp_stage_{uuid.uuid4().hex[:8]}"
    
    try:
        with conn.cursor() as cur:
            # 1. Create a bulletproof text-only staging table
            temp_cols = ", ".join([f'"{col}" TEXT' for col in csv_cols])
            cur.execute(f"CREATE TEMP TABLE {staging_table} ({temp_cols}) ON COMMIT DROP")
            
            # 2. Pipe the CSV directly to PostgreSQL, destroying \x00 in transit
            stream = CleanCSVStream(file_path)
            cur.copy_expert(f"COPY {staging_table} FROM STDIN WITH (FORMAT csv, HEADER true)", stream)
            stream.close()
            
            # 3. Native Server-Side Transformation (C-Level execution)
            insert_sql = generate_insert_sql(model, csv_cols, staging_table, filename)
            cur.execute(insert_sql)
            
        session.commit()
        logger.info(f"Successfully loaded: {filename}")
        
    except Exception as e:
        session.rollback()
        logger.error(f"Failed loading {filename}: {e}")
        raise e

# -----------------------------------------------------------------------------
# Orchestration & Idempotency
# -----------------------------------------------------------------------------
def init_db():
    SQLModel.metadata.create_all(engine)
    with Session(engine) as session:
        # Create ultra-fast O(1) state table
        session.execute(text("CREATE TABLE IF NOT EXISTS ingestion_state (filename TEXT PRIMARY KEY)"))
        session.commit()
        
        processed = {r[0] for r in session.execute(text("SELECT filename FROM ingestion_state"))}

        # Load Core Datasets
        for path, model in INGESTION_PLAN:
            if not os.path.exists(path): continue
            fname = os.path.basename(path)
            if fname not in processed:
                try:
                    brutal_ingest(session, path, model, fname)
                    session.execute(text("INSERT INTO ingestion_state (filename) VALUES (:f)"), {"f": fname})
                    session.commit()
                except Exception:
                    pass

        # Load Activity Logs
        if os.path.exists(ACTIVITY_LOGS_PATH):
            log_files = sorted([f for f in os.listdir(ACTIVITY_LOGS_PATH) if f.endswith(".csv")], 
                               key=lambda x: int(re.search(r"\d+", x).group() if re.search(r"\d+", x) else 0))
            for fname in log_files:
                if fname not in processed:
                    try:
                        path = os.path.join(ACTIVITY_LOGS_PATH, fname)
                        brutal_ingest(session, path, ActivityLogs, fname)
                        session.execute(text("INSERT INTO ingestion_state (filename) VALUES (:f)"), {"f": fname})
                        session.commit()
                    except Exception:
                        pass

if __name__ == "__main__":
    init_db()